package org.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGameTurn<M extends BaseGameTurn<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除;1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除;1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 项目编号
	 */
	public void setGameNo(java.lang.String gameNo) {
		set("game_no", gameNo);
	}
	
	/**
	 * 项目编号
	 */
	public java.lang.String getGameNo() {
		return getStr("game_no");
	}
	
	/**
	 * 场次编号,作为场次的主键唯一存在
	 */
	public void setTurnNo(java.lang.String turnNo) {
		set("turn_no", turnNo);
	}
	
	/**
	 * 场次编号,作为场次的主键唯一存在
	 */
	public java.lang.String getTurnNo() {
		return getStr("turn_no");
	}
	
	/**
	 * 名称 本场名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称 本场名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 比赛场地 比赛场地
	 */
	public void setPlace(java.lang.String place) {
		set("place", place);
	}
	
	/**
	 * 比赛场地 比赛场地
	 */
	public java.lang.String getPlace() {
		return getStr("place");
	}
	
	/**
	 * 比赛时间 比赛时间
	 */
	public void setTime(java.lang.String time) {
		set("time", time);
	}
	
	/**
	 * 比赛时间 比赛时间
	 */
	public java.lang.String getTime() {
		return getStr("time");
	}
	
	/**
	 * 参赛人数 参加本场比赛的人数
	 */
	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	/**
	 * 参赛人数 参加本场比赛的人数
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}
	
}
