package org.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProcess<M extends BaseProcess<M>> extends Model<M> implements IBean {

	/**
	 * 主键;主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键;主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间;创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间;创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间;更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间;更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除;0-未删除;1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除;0-未删除;1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 流程编号
	 */
	public void setProcessNo(java.lang.String processNo) {
		set("process_no", processNo);
	}
	
	/**
	 * 流程编号
	 */
	public java.lang.String getProcessNo() {
		return getStr("process_no");
	}
	
	/**
	 * 流程名称;描述流程,如开始报名等
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 流程名称;描述流程,如开始报名等
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
}
