package org.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除;1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除;1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 学号/工号/账号 表示登录时用的账号
	 */
	public void setUserNo(java.lang.String userNo) {
		set("user_no", userNo);
	}
	
	/**
	 * 学号/工号/账号 表示登录时用的账号
	 */
	public java.lang.String getUserNo() {
		return getStr("user_no");
	}
	
	/**
	 * 学院编号 表示学院编号(管理员为空)
	 */
	public void setSchoolNo(java.lang.String schoolNo) {
		set("school_no", schoolNo);
	}
	
	/**
	 * 学院编号 表示学院编号(管理员为空)
	 */
	public java.lang.String getSchoolNo() {
		return getStr("school_no");
	}
	
	/**
	 * 姓名 表示姓名(管理员和公共账号为空)
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 姓名 表示姓名(管理员和公共账号为空)
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 密码 加密后的密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码 加密后的密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 手机号 手机号(管理员和公共账号为空)
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号 手机号(管理员和公共账号为空)
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 性别 0-男生;1-女生(管理员和公共账号为空)
	 */
	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别 0-男生;1-女生(管理员和公共账号为空)
	 */
	public java.lang.Integer getSex() {
		return getInt("sex");
	}
	
}
