package org.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComplaint<M extends BaseComplaint<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除;1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除;1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 申诉编号
	 */
	public void setComplaintNo(java.lang.String complaintNo) {
		set("complaint_no", complaintNo);
	}
	
	/**
	 * 申诉编号
	 */
	public java.lang.String getComplaintNo() {
		return getStr("complaint_no");
	}
	
	/**
	 * 申诉类别 0-成绩错误;1-举报他人;2-其他错误
	 */
	public void setCategory(java.lang.Integer category) {
		set("category", category);
	}
	
	/**
	 * 申诉类别 0-成绩错误;1-举报他人;2-其他错误
	 */
	public java.lang.Integer getCategory() {
		return getInt("category");
	}
	
	/**
	 * 学号/工号 表示提交申诉的人
	 */
	public void setUserNo(java.lang.String userNo) {
		set("user_no", userNo);
	}
	
	/**
	 * 学号/工号 表示提交申诉的人
	 */
	public java.lang.String getUserNo() {
		return getStr("user_no");
	}
	
	/**
	 * 描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 状态 0-未处理;1-已处理
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 状态 0-未处理;1-已处理
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	/**
	 * 处理结果 用户提交时为空,管理员处理后将结果写入
	 */
	public void setResult(java.lang.String result) {
		set("result", result);
	}
	
	/**
	 * 处理结果 用户提交时为空,管理员处理后将结果写入
	 */
	public java.lang.String getResult() {
		return getStr("result");
	}
	
}
