package org.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCookie<M extends BaseCookie<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除;1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除;1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * uuno token所属对象
	 */
	public void setUuno(java.lang.String uuno) {
		set("uuno", uuno);
	}
	
	/**
	 * uuno token所属对象
	 */
	public java.lang.String getUuno() {
		return getStr("uuno");
	}
	
	/**
	 * access_token 存储token信息
	 */
	public void setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
	}
	
	/**
	 * access_token 存储token信息
	 */
	public java.lang.String getAccessToken() {
		return getStr("access_token");
	}
	
	/**
	 * 有效时间 cookie有效时间，秒
	 */
	public void setExpiresIn(java.math.BigInteger expiresIn) {
		set("expires_in", expiresIn);
	}
	
	/**
	 * 有效时间 cookie有效时间，秒
	 */
	public java.math.BigInteger getExpiresIn() {
		return get("expires_in");
	}
	
	/**
	 * 过期时间 过期时间，时间戳
	 */
	public void setExpiresTime(java.math.BigInteger expiresTime) {
		set("expires_time", expiresTime);
	}
	
	/**
	 * 过期时间 过期时间，时间戳
	 */
	public java.math.BigInteger getExpiresTime() {
		return get("expires_time");
	}
	
}
