package org.common.module;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("complaint", "id", Complaint.class);
		arp.addMapping("cookie", "id", Cookie.class);
		arp.addMapping("enroll", "id", Enroll.class);
		arp.addMapping("game", "id", Game.class);
		arp.addMapping("game_turn", "id", GameTurn.class);
		arp.addMapping("grade", "id", Grade.class);
		arp.addMapping("process", "id", Process.class);
		arp.addMapping("referee", "id", Referee.class);
		arp.addMapping("school", "id", School.class);
		arp.addMapping("team", "id", Team.class);
		arp.addMapping("team_mate", "id", TeamMate.class);
		arp.addMapping("user", "id", User.class);
	}
}

