package org.common.module;

import org.common.module.base.BaseComplaint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Complaint extends BaseComplaint<Complaint> {
	public static final Complaint dao = new Complaint().dao();
}
