package org.common.module;

import org.common.module.base.BaseCookie;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cookie extends BaseCookie<Cookie> {
	public static final Cookie dao = new Cookie().dao();
}
