package org.common.module;

import org.common.module.base.BaseEnroll;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Enroll extends BaseEnroll<Enroll> {
	public static final Enroll dao = new Enroll().dao();
}
