package org.common.module;

import org.common.module.base.BaseGame;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Game extends BaseGame<Game> {
	public static final Game dao = new Game().dao();
}
