package org.common.module;

import org.common.module.base.BaseGameTurn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameTurn extends BaseGameTurn<GameTurn> {
	public static final GameTurn dao = new GameTurn().dao();
}
