package org.common.module;

import org.common.module.base.BaseGameType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameType extends BaseGameType<GameType> {
	public static final GameType dao = new GameType().dao();
}
