package org.common.module;

import org.common.module.base.BaseGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Grade extends BaseGrade<Grade> {
	public static final Grade dao = new Grade().dao();
}
