package org.common.module;

import org.common.module.base.BaseProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Process extends BaseProcess<Process> {
	public static final Process dao = new Process().dao();
}
