package org.common.module;

import org.common.module.base.BaseReferee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Referee extends BaseReferee<Referee> {
	public static final Referee dao = new Referee().dao();
}
