package org.common.module;

import org.common.module.base.BaseSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class School extends BaseSchool<School> {
	public static final School dao = new School().dao();
}
