package org.common.module;

import org.common.module.base.BaseTeamMate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamMate extends BaseTeamMate<TeamMate> {
	public static final TeamMate dao = new TeamMate().dao();
}
