package org.common.module;

import org.common.module.base.BaseTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Team extends BaseTeam<Team> {
	public static final Team dao = new Team().dao();
}
